model:
  base_learning_rate: 4.5e-6
  target: models.vqargan_automask.VQARAutoMaskModel
  params:
    embed_dim: 256
    n_embed: 1024
    finetune: True
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 64
      ch_mult: [1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        perceptual_weight: 0
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 5000
        disc_weight: 0.8
        codebook_weight: 1.0
        BG_weight: 2
        FG_weight: 3
        mask_bound_weight: 5
        mask_binarization_weight: 10
        mask_loss_weight: 1
        BG_sparsity_ratio: 150

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 10
    num_workers: 6
    train:
      target: data.custom.CustomTrain
      params:
        training_images_list_file: data_txts/tennis_train.txt
        size: [96, 256]
        skip_frames: 4
    validation:
      target: data.custom.CustomTest
      params:
        test_images_list_file: data_txts/tennis_test.txt
        size: [96, 256]

